name: Add Issues/PRs to Project Board

on:
  issues:
    types: [opened, labeled, milestoned]
  pull_request:
    types: [opened, labeled, milestoned]

jobs:
  add-to-project:
    name: Add item to the Translation Project
    runs-on: ubuntu-latest
    
    steps:
      - name: Add to Project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/davidrsch/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
